name: build

permissions: read-all

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - name: Install Go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2.1.5
        with:
          go-version: 1.18

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.45.0

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v -tags -race -shuffle=on -coverprofile="coverage.txt" ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v2.1.0
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false
